# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunkChanges.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunkChanges.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x63hunkChanges.proto\"9\n\x0c\x43hunkChanges\x12\x11\n\thashKnown\x18\x01 \x02(\x08\x12\x16\n\x06\x63hunks\x18\x02 \x03(\x0b\x32\x06.Chunk\"8\n\x05\x43hunk\x12\t\n\x01x\x18\x01 \x02(\x04\x12\t\n\x01y\x18\x02 \x02(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x04\x12\x0b\n\x03\x65of\x18\x04 \x02(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHUNKCHANGES = _descriptor.Descriptor(
  name='ChunkChanges',
  full_name='ChunkChanges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashKnown', full_name='ChunkChanges.hashKnown', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='ChunkChanges.chunks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=79,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Chunk.x', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Chunk.y', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Chunk.data', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eof', full_name='Chunk.eof', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=137,
)

_CHUNKCHANGES.fields_by_name['chunks'].message_type = _CHUNK
DESCRIPTOR.message_types_by_name['ChunkChanges'] = _CHUNKCHANGES
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK

ChunkChanges = _reflection.GeneratedProtocolMessageType('ChunkChanges', (_message.Message,), dict(
  DESCRIPTOR = _CHUNKCHANGES,
  __module__ = 'chunkChanges_pb2'
  # @@protoc_insertion_point(class_scope:ChunkChanges)
  ))
_sym_db.RegisterMessage(ChunkChanges)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'chunkChanges_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  ))
_sym_db.RegisterMessage(Chunk)


# @@protoc_insertion_point(module_scope)
